version: '3.8'
services:
  # Backend API
  app-backend:
    build: ./backend
    environment:
      - GO_ENV=production
      - FIREBASE_CREDENTIALS=/app/firebase-key.json
    volumes:
      - ./firebase-key.json:/app/firebase-key.json
    ports:
      - "8080:8080"
    restart: always

  # Nginx Reverse Proxy (for API)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      # - ./certbot/conf:/etc/letsencrypt
      # - ./certbot/www:/var/www/certbot
    depends_on:
      - app-backend
    restart: always
